apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: go-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: go.counter.com
    http:
      paths:
      - backend:
          serviceName: go-app-service
          servicePort: 8090