--- 
agent: 
  enabled: false
master: 
  ingress: 
    annotations: 
      kubernetes.io/ingress.class: nginx
    enabled: true
  installPlugins: 
    - "kubernetes:1.18.1"
    - "workflow-aggregator:2.6"
    - "workflow-job:2.33"
    - "credentials-binding:1.19"
    - "git:3.11.0"
    - "pipeline-github-lib:1.0"
    - "ghprb:1.39.0"
  scriptApproval: 
    - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
    - "new groovy.json.JsonSlurperClassic"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String"
    - "method java.util.Collection toArray"
    - "staticMethod org.kohsuke.groovy.sandbox.impl.Checker checkedCall java.lang.Object boolean boolean java.lang.String java.lang.Object[]"
    - "staticMethod org.kohsuke.groovy.sandbox.impl.Checker checkedGetProperty java.lang.Object boolean boolean java.lang.Object"
  serviceType: ClusterIP
  tag: lts
rbac: 
  create: false
