apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gochart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gochart.name" . }}
    helm.sh/chart: {{ include "gochart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gochart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gochart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          env:
            - name: ERVCP_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: host
            - name: ERVCP_DB_PW
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: pass
            - name: ERVCP_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: port
      imagePullSecrets: 
        - name: myregistrykey
